[workspace]
members = [
    "service",
    "signer",
    "signer-ffi",
    "signer-wasm",
    "ledger"
    "hfuzz-signer",
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
