[package]
name = "filecoin-signer"
version = "0.1.0"
authors = ["Zondax <info@zondax.ch>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/Zondax/filecoin-rs"
description =""

[dependencies]
thiserror = "1.0"
base64 = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.11.1"
rayon = "1"

bls-signatures = "0.5.0"

# Crypto related
hex = "0.4.2"
getrandom="0.1.14"
libsecp256k1 = "0.3.5"
blake2b_simd = "0.5.10"
hmac = "0.7.1"
zeroize = { version = "1.1", default-features = false, features = ["zeroize_derive"] }
sha2 = "0.8.1"

# logging
log="0.4"
env_logger = "0.7"

ffi-support = { optional = true, version = "0.4" }

# TODO: Update once crates are available
vm = { git = "https://github.com/zondax/forest", tag="testnet3" }
forest_message = { git = "https://github.com/zondax/forest", tag="testnet3" }
forest_address = { git = "https://github.com/zondax/forest", tag="testnet3" }
forest_encoding = { git = "https://github.com/zondax/forest", tag="testnet3" }

# TODO: Maybe we can replace these with something leaner
tiny-bip39 = "0.7.3"
num_bigint_chainsafe = { package = "forest_bigint", git = "https://github.com/zondax/forest", tag="testnet3"}

bip44 = { git = "https://github.com/Zondax/ledger-rs", branch = "feature/refactoring-wasm"}


[dev-dependencies]
rand_xorshift = "0.2.0"
rand = "0.7"

[features]
with-ffi-support = ["ffi-support"]
